"""Embed an immutable build identity into skodun sdists and wheels.

Source checkouts do not ship ``skodun._build``; provenance falls back to git.
A git-built sdist carries the identity so a later wheel built from that sdist
(without ``.git``) still authenticates. Anonymous ``commit=null`` wheels are
refused.
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path

from hatchling.builders.hooks.plugin.interface import BuildHookInterface

_TEMPLATE = """\
# Generated by hatch_build.py at sdist/wheel build time. Not present in checkouts.
COMMIT = {commit!r}
SCHEMA_VERSION = {schema}
VERSION = {version!r}
"""

_COMMIT_RE = re.compile(
    r"^COMMIT = ['\"]([0-9a-f]{40}(?:-(?:dirty|unknown))?)['\"]",
    re.MULTILINE)


class CustomBuildHook(BuildHookInterface):
    PLUGIN_NAME = "custom"

    def initialize(self, version, build_data):
        if self.target_name not in {"wheel", "sdist"}:
            return
        root = Path(self.root)
        commit = _git_commit(root) or _existing_embedded_commit(root)
        if commit is None:
            raise RuntimeError(
                "refusing to build skodun without a git HEAD identity or an "
                "embedded commit from a git-built sdist")
        out = Path(self.directory) / "skodun_embedded_build.py"
        out.write_text(_TEMPLATE.format(
            commit=commit,
            schema=_schema_version(root),
            version=self.metadata.version,
        ), encoding="utf-8")
        dest = ("skodun/_build.py" if self.target_name == "wheel"
                else "src/skodun/_build.py")
        build_data.setdefault("force_include", {})
        build_data["force_include"][str(out)] = dest


def _existing_embedded_commit(root: Path) -> str | None:
    """Commit already baked into a git-built sdist, or None."""
    for candidate in (
            root / "src" / "skodun" / "_build.py",
            root / "skodun" / "_build.py"):
        try:
            text = candidate.read_text(encoding="utf-8")
        except OSError:
            continue
        match = _COMMIT_RE.search(text)
        if match:
            return match.group(1)
    return None


def _git_commit(root: Path) -> str | None:
    top = subprocess.run(
        ["git", "-C", str(root), "rev-parse", "--show-toplevel"],
        capture_output=True, text=True, timeout=10)
    if top.returncode != 0:
        return None
    try:
        if Path(top.stdout.strip()).resolve() != root.resolve():
            return None
    except OSError:
        return None
    head = subprocess.run(
        ["git", "-C", str(root), "rev-parse", "HEAD"],
        capture_output=True, text=True, timeout=10)
    if head.returncode != 0:
        return None
    commit = head.stdout.strip()
    if len(commit) != 40 or any(ch not in "0123456789abcdef" for ch in commit):
        return None
    status = subprocess.run(
        ["git", "-C", str(root), "status", "--porcelain"],
        capture_output=True, text=True, timeout=10)
    if status.returncode != 0:
        return f"{commit}-unknown"
    if status.stdout.strip():
        return f"{commit}-dirty"
    return commit


def _schema_version(root: Path) -> int:
    text = (root / "src" / "skodun" / "store.py").read_text(encoding="utf-8")
    for line in text.splitlines():
        if line.startswith("SCHEMA_VERSION"):
            return int(line.split("=", 1)[1].strip())
    raise RuntimeError("SCHEMA_VERSION not found")
