"""Embed an immutable build identity into skodun wheels.

Source checkouts do not ship ``skodun._build``; provenance falls back to git.
A wheel without a git HEAD identity is refused rather than published as
anonymous ``commit=null``.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

from hatchling.builders.hooks.plugin.interface import BuildHookInterface

_TEMPLATE = """\
# Generated by hatch_build.py at wheel build time. Not present in checkouts.
COMMIT = {commit!r}
SCHEMA_VERSION = {schema}
VERSION = {version!r}
"""


class CustomBuildHook(BuildHookInterface):
    PLUGIN_NAME = "custom"

    def initialize(self, version, build_data):
        if self.target_name != "wheel":
            return
        root = Path(self.root)
        commit = _git_commit(root)
        if commit is None:
            raise RuntimeError(
                "refusing to build a skodun wheel without a git HEAD identity")
        out = Path(self.directory) / "skodun_embedded_build.py"
        out.write_text(_TEMPLATE.format(
            commit=commit,
            schema=_schema_version(root),
            version=self.metadata.version,
        ), encoding="utf-8")
        build_data.setdefault("force_include", {})
        build_data["force_include"][str(out)] = "skodun/_build.py"


def _git_commit(root: Path) -> str | None:
    head = subprocess.run(
        ["git", "-C", str(root), "rev-parse", "HEAD"],
        capture_output=True, text=True, timeout=10)
    if head.returncode != 0:
        return None
    commit = head.stdout.strip()
    if len(commit) != 40 or any(ch not in "0123456789abcdef" for ch in commit):
        return None
    status = subprocess.run(
        ["git", "-C", str(root), "status", "--porcelain"],
        capture_output=True, text=True, timeout=10)
    if status.returncode != 0:
        return f"{commit}-unknown"
    if status.stdout.strip():
        return f"{commit}-dirty"
    return commit


def _schema_version(root: Path) -> int:
    text = (root / "src" / "skodun" / "store.py").read_text(encoding="utf-8")
    for line in text.splitlines():
        if line.startswith("SCHEMA_VERSION"):
            return int(line.split("=", 1)[1].strip())
    raise RuntimeError("SCHEMA_VERSION not found")
